name: Commitlint

on: [push]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: true # If its realy needed?
          configFile: .commitlintrc.yaml